language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

notifications:
  irc: "chat.freenode.net#omnomhub"

before_script: composer install -n

script: "`pwd`/bin/codecept run -c `pwd`/codeception.travis.yml unit"
