language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install -n
  - chmod 0777 tests/_log -R

script: "`pwd`/bin/codecept run -c `pwd`/codeception.yml"