parameters:
    group.class: Omnomhub\Bundle\MainBundle\Model\Group\Group
    message.class: Omnomhub\Bundle\MainBundle\Model\Group\Message
    ingredient.class: Omnomhub\Bundle\MainBundle\Model\Recipe\Ingredient
    recipe.class: Omnomhub\Bundle\MainBundle\Model\Recipe\Recipe
    userprovider.class: Omnomhub\Bundle\MainBundle\Security\User\Neo4jUserProvider

services:
    group:
        class: %group.class%
        arguments: ["@neo4j.client"]
    message:
        class: %message.class%
        arguments: ["@neo4j.client"]
    ingredient:
        class: %ingredient.class%
        arguments: ["@neo4j.client"]
    recipe:
        class: %recipe.class%
        arguments: ["@neo4j.client"]
    userprovider:
        class: %userprovider.class%
        arguments: ["@neo4j.client"]