---
- name: NGINX | Disable Default Host Config
  command: rm /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
  notify: restart nginx

- name: NGINX | Copy Host Config
  action: template src=../files/nginx-omnomhub.conf dest=/etc/nginx/sites-available/omnomhub.conf

- name: NGINX | Enable Host Config
  command: ln -s /etc/nginx/sites-available/omnomhub.conf /etc/nginx/sites-enabled/omnomhub.conf
  notify: restart nginx

- name: NGINX | Ensure application files are present
  file: path={{ document_root }} state=directory

- name: PHP | Remove default pool config
  command: rm /etc/php5/fpm/pool.d/www.conf
  notify: restart fpm

- name: PHP | Copy Pool Config
  action: template src=../files/php-fpm-omnomhub.conf dest=/etc/php5/fpm/pool.d/omnomhub.conf
  notify: restart fpm

- name: NEO4J | Copy Server Config
  action: template src=../files/neo4j-server.properties dest=/etc/neo4j/neo4j-server.properties
  notify: restart neo4j