---
- hosts: all
  sudo: true
  vars:
    root_folder: /var/www/omnomhub
    document_root: "{{ root_folder }}/web/"
    write_to_folder: /dev/shm/omnomhub
    dbname: omnomhub
    dbuser: root
    dbpasswd: root
  tasks:
    - include: tasks/common.yml
    - include: tasks/build.yml
    - include: tasks/development.yml
    - include: tasks/host.yml
    - include: tasks/app.yml

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart fpm
      service: name=php5-fpm state=restarted

    - name: restart supervisor
      service: name=supervisord state=restarted

    - name: reload supervisor
      command: supervisorctl reload

    - name: restart neo4j
      service: name=neo4j-service state=restarted
